# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EasyDem
                                 A QGIS plugin
 DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-01
        git sha              : $Format:%H$
        copyright            : (C) 2026 by FARM Analytica
        email                : livia.scopel@farmanalytica.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .resources import *

from .easy_dialog import EasyDemDialog
from .services.gee_service import GEEService
import os.path


class EasyDem:
    def __init__(self, interface):

        self.interface = interface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "EasyDem_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = "&EasyDEM"

        self.first_start = None

    def tr(self, message):

        return QCoreApplication.translate("easydem", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.interface.addToolBarIcon(action)

        if add_to_menu:
            self.interface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def init_gui(self):

        icon_path = ":/plugins/easy/icon.png"
        self.add_action(
            icon_path,
            text=self.tr(""),
            callback=self.run,
            parent=self.interface.mainWindow(),
        )

        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.interface.removePluginMenu("&EasyDEM", action)
            self.interface.removeToolBarIcon(action)

    def run(self):

        if self.first_start:
            self.first_start = False
            self.gee_service = GEEService()
            self.dlg = EasyDemDialog()

            saved_project_id = self.gee_service.get_saved_project_id()
            if saved_project_id:
                self.dlg.project_id_input.setText(saved_project_id)

            self.dlg.project_id_input.textChanged.connect(
                self.gee_service.save_project_id
            )

            self.dlg.btn_authenticate.clicked.connect(self.handle_authentication)

            self.dlg.btn_reset_auth.clicked.connect(self.handle_reset_authentication)

        self.dlg.show()
        result = self.dlg.exec_()
        if result:
            pass

    def handle_authentication(self):
        project_id = self.dlg.project_id_input.text()
        if not project_id:
            self.dlg.pop_warning("Missing Project ID.")
            return

        try:
            self.gee_service.authenticate(project_id)
            self.dlg.pop_message("Authentication successful!")

        except Exception as e:
            self.dlg.pop_warning(str(e))

    def handle_reset_authentication(self):
        try:
            msg = self.gee_service.reset_authentication()
            if msg:
                self.dlg.pop_message(msg)
        except (FileNotFoundError, RuntimeError, OSError) as e:
            self.dlg.pop_warning(str(e))
