# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EasyDem
                                 A QGIS plugin
 DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-01
        git sha              : $Format:%H$
        copyright            : (C) 2026 by FARM Analytica
        email                : livia.scopel@farmanalytica.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import re
import os.path

from qgis.PyQt.QtCore import (
    QSettings,
    QTranslator,
    QCoreApplication,
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import (
    QgsRasterLayer,
    QgsColorRampShader,
    QgsProject,
    QgsRasterShader,
    QgsSingleBandPseudoColorRenderer,
    QgsStyle,
    QgsLayerTreeLayer,
)

from .resources import *

from .easy_dialog import EasyDemDialog
from .services.gee_service import GEEService
from .services.aoi_service import AOIService
from .services.dem_service import DEMService


class EasyDem:
    """
    Main plugin class for EasyDEM QGIS plugin.

    Manages plugin initialization, GUI setup, and authentication workflow.
    """

    def __init__(self, interface):
        """
        Initialize EasyDEM plugin.

        Args:
            interface: QGIS interface instance.
        """

        self.interface = interface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "EasyDem_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = "&EasyDEM"

        self.first_start = None

    def tr(self, message):
        """
        Translate a message string.

        Args:
            message: Message to translate.

        Returns:
            Translated message string.
        """
        return QCoreApplication.translate("easydem", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """
        Add an action to the toolbar and/or menu.

        Args:
            icon_path: Path to the action icon.
            text: Action display text.
            callback: Function to call when action is triggered.
            enabled_flag: Whether action is enabled initially.
            add_to_menu: Whether to add action to plugin menu.
            add_to_toolbar: Whether to add action to toolbar.
            status_tip: Tooltip text.
            whats_this: Help text.
            parent: Parent widget.

        Returns:
            The created QAction object.
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.interface.addToolBarIcon(action)

        if add_to_menu:
            self.interface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Initialize the plugin GUI."""
        icon_path = ":/plugins/easy/icon.png"
        self.add_action(
            icon_path,
            text=self.tr(""),
            callback=self.run,
            parent=self.interface.mainWindow(),
        )

        self.first_start = True

    def unload(self):
        """Remove the plugin from QGIS."""
        for action in self.actions:
            self.interface.removePluginMenu("&EasyDEM", action)
            self.interface.removeToolBarIcon(action)

    def run(self):
        """Display the plugin dialog and handle user interaction."""
        if self.first_start:
            self.first_start = False
            self.gee_service = GEEService()
            self.dlg = EasyDemDialog()

            saved_project_id = self.gee_service.get_saved_project_id()
            if saved_project_id:
                self.dlg.project_id_input.setText(saved_project_id)

            self.dlg.project_id_input.textChanged.connect(
                self.gee_service.save_project_id
            )

            self.dlg.btn_authenticate.clicked.connect(self.handle_authentication)

            self.dlg.btn_reset_auth.clicked.connect(self.handle_reset_authentication)

            self.dlg.btn_get_aoi.clicked.connect(self.handle_get_aoi)

        self.dlg.show()
        result = self.dlg.exec_()
        if result:
            pass

    def handle_authentication(self):
        """
        Handle Google Earth Engine authentication flow.

        Validates project ID and performs authentication, displaying
        appropriate messages on success or failure.
        """
        project_id = self.dlg.project_id_input.text()
        if not project_id:
            self.dlg.pop_message("Missing Project ID.", "warning")
            return

        project_id_pattern = r"^[a-z][a-z0-9-]{4,28}[a-z0-9]$"

        if not re.match(project_id_pattern, project_id):
            self.dlg.pop_message("Invalid Project ID.", "warning")
            return

        try:
            self.gee_service.authenticate(project_id)
            self.dlg.show_aoi_page()
            self.dlg.pop_message("Authentication successful!", "info")

        except Exception as e:
            self.dlg.pop_message(str(e), "warning")

    def handle_reset_authentication(self):
        """Reset Google Earth Engine authentication credentials."""
        try:
            msg = self.gee_service.reset_authentication()
            if msg:
                self.dlg.pop_message(msg, "info")
        except (FileNotFoundError, RuntimeError, OSError) as e:
            self.dlg.pop_message(str(e), "warning")

    def handle_get_aoi(self):
        """Load the AOI from the selected layer and store it for downstream use."""
        try:
            layer = self.dlg.layer_combo.currentLayer()

            if not layer:
                self.dlg.pop_message("Select a layer.", "warning")
                return

            aoi = AOIService.get_aoi_from_layer(layer)
            dem_path = DEMService.download_dem(aoi)

            self._load_dem_to_qgis(dem_path)

            self.dlg.pop_message("DEM loaded sucessfully", "info")

        except Exception as e:
            self.dlg.pop_message(str(e), "warning")

    def _build_color_renderer(
        self, provider, min_val, max_val
    ) -> QgsSingleBandPseudoColorRenderer:
        """Build the color ramp for the layer"""
        color_ramp = QgsStyle().defaultStyle().colorRamp("Magma")
        if not color_ramp:
            raise RuntimeError("Color ramp 'Magma' not found in QGIS style library.")

        num_stops = 5
        step = (max_val - min_val) / (num_stops - 1)
        color_ramp_items = [
            QgsColorRampShader.ColorRampItem(
                min_val + i * step, color_ramp.color(i / (num_stops - 1))
            )
            for i in range(num_stops)
        ]

        color_ramp_shader = QgsColorRampShader()
        color_ramp_shader.setColorRampType(QgsColorRampShader.Interpolated)
        color_ramp_shader.setColorRampItemList(color_ramp_items)

        raster_shader = QgsRasterShader()
        raster_shader.setRasterShaderFunction(color_ramp_shader)

        renderer = QgsSingleBandPseudoColorRenderer(provider, 1, raster_shader)
        renderer.setClassificationMin(min_val)
        renderer.setClassificationMax(max_val)
        return renderer

    def _load_dem_to_qgis(self, path: str) -> QgsRasterLayer:
        """
        Load a DEM GeoTIFF into QGIS with a Magma color ramp renderer.

        Args:
            path: Absolute path to the GeoTIFF file.

        Returns:
            The loaded and styled QgsRasterLayer.

        Raises:
            RuntimeError: If the raster layer is invalid.
        """
        raster_layer = QgsRasterLayer(path, "DEM (Copernicus)")
        if not raster_layer.isValid():
            raise RuntimeError("Failed to load DEM into QGIS.")

        provider = raster_layer.dataProvider()
        stats = provider.bandStatistics(1)
        min_val, max_val = stats.minimumValue, stats.maximumValue

        renderer = self._build_color_renderer(provider, min_val, max_val)
        raster_layer.setRenderer(renderer)

        QgsProject.instance().addMapLayer(raster_layer, False)
        QgsProject.instance().layerTreeRoot().insertChildNode(
            0, QgsLayerTreeLayer(raster_layer)
        )
        raster_layer.triggerRepaint()

        return raster_layer
